package com.windchillWS.enums;

public enum AttributesOthers {

	areaCompetencia("empresa.AREA_COMPETENCIA"),
	classeServico("empresa.CLASSE_SERVICO"),
	contratoReferencia("empresa.CONTRATO_REFERENCIA"),
	controleRespondida("empresa.DT_CONTROLE_RESPONDIDA"),
	copyTo("empresa.COPY_TO"),
	dataAssinatura("empresa.DATA_ASSINATURA"),
	dataCedoc("empresa.DATA_CEDOC"),
	dataCriacao("empresa.DATA_CRIACAO"),
	dataEmissao("data_emissao"),
	dataFim("data_fim"),
	dataempresa("empresa.DATA_empresa"),
	dataInicial("empresa.DATA_INICIAL"),
	dataInicio("data_inicio"),
	dataInspecao("empresa.DATA_INSPECAO"),
	dataProtocolo("data_protocolo"),
	dataRecb("empresa.DATA_RECB"),
	dataRecebimento("data_recebimento"),
	dataResp("empresa.DATA_RESP"),
	dataTdpis("empresa.DATA_TDPIS"),
	dateApproval("empresa.DATE_APPROVAL"),
	description("description"),
	destinatarioPj("empresa.DESTINATARIO_PJ"),
	diretoriaEmissora("empresa.DIRETORIA_EMISSORA"),
	docReferencia("empresa.DOC_REFERENCIA"),
	docRelacionado("empresa.DOC_RELACIONADO"),
	dtApproval("empresa.DT_APPROVAL"),
	dtEmissao("empresa.DT_EMISSAO"),
	dtProposal("empresa.DT_PROPOSAL"),
	dtProtocoloAtech("dt_protocolo_atech"),
	dtProtocoloCbs("dt_protocolo_cbs"),
	dtProtocoloDcns("dt_protocolo_dcns"),
	dtProtocoloEbn("dt_protocolo_ebn"),
	dtProtocoloEmgp("dt_protocolo_emgp"),
	dtProtocoloMb("dt_protocolo_mb"),
	dtProtocoloNuclep("dt_protocolo_nuclep"),
	dtProtocoloTerc("dt_protocolo_terc"),
	dtResponse("empresa.DT_RESPONSE"),
	dtRevision("empresa.DT_REVISION"),
	empresaEmitente("empresa_emitente"),
	faseProjeto("empresa.FASE_PROJETO"),
	fegiDisciplina("empresa.FEGI_DISCIPLINA"),
	fegiSubmarino("empresa.FEGI_SUBMARINO"),
	fornecedor("fornecedor"),
	funcBigrama("empresa.SIT_FUNC_BIGRAMA"),
	geograficaOutros("empresa.SIT_GEOGRAFICA_OUTROS"),
	gerenciaImp("empresa.GERENCIA_IMP"),
	gerenciaLider("empresa.GERENCIA_LIDER"),
	gerenciaNotif("empresa.GERENCIA_NOTIF"),
	gerenciaResp("empresa.GERENCIA_RESP"),
	globalTipoMaterial("global.TIPO_MATERIAL"),
	grauPrioridade("empresa.GRAU_PRIORIDADE"),
	guiaRecebimento("guia_recebimento"),
	empresaAgente("empresa.AGENTE"),
	empresaAnexo("empresa.ANEXO"),
	empresaAno("empresa.ANO"),
	empresaAnswer("empresa.ANSWER"),
	empresaAplicacao("empresa.APLICACAO"),
	empresaArea("empresa.AREA"),
	empresaArrival("empresa.ARRIVAL"),
	empresaAssunto("empresa.ASSUNTO"),
	empresaAuditados("empresa.AUDITADOS"),
	empresaAuditores("empresa.AUDITORES"),
	empresaAutor("empresa.AUTOR"),
	empresaAutoria("empresa.AUTORIA"),
	empresaBatch("empresa.BATCH"),
	empresaCarga("empresa.CARGA"),
	empresaCategoria("empresa.CATEGORIA"),
	empresaCategory("empresa.CATEGORY"),
	empresaComentarios("empresa.COMENTARIOS"),
	empresaContainer("empresa.CONTAINER"),
	empresaContext("empresa.CONTEXT"),
	empresaContratada("empresa.CONTRATADA"),
	empresaContratante("empresa.CONTRATANTE"),
	empresaContrato("empresa.CONTRATO"),
	empresaControle("empresa.CONTROLE"),
	empresaCorretion("empresa.empresa_CORRETION"),
	empresaCos("empresa.COS"),
	empresaCriticity("empresa.CRITICITY"),
	empresaCtc("empresa.CTC"),
	empresaCte("empresa.CTE"),
	empresaData("empresa.DATA"),
	empresaData11("empresa.DATA11"),
	empresaData12("empresa.DATA12"),
	empresaData13("empresa.DATA13"),
	empresaData21("empresa.DATA21"),
	empresaData22("empresa.DATA22"),
	empresaData32("empresa.DATA32"),
	empresaData43("empresa.DATA43"),
	empresaData51("empresa.DATA51"),
	empresaData61("empresa.DATA61"),
	empresaData71("empresa.DATA71"),
	empresaData72("empresa.DATA72"),
	empresadataEmissao("empresa.DATA_EMISSAO"),
	empresaDataFim("empresa.DATA_FIM"),
	empresaDataProtocolo("empresa.DATA_PROTOCOLO1"),
	empresaDataRecebimento("empresa.DATA_RECEBIMENTO"),
	empresaDeadline("empresa.DEADLINE"),
	empresaDelegar("empresa.DELEGAR"),
	empresaDepto("empresa.DEPTO"),
	empresaDestinatario("empresa.DESTINATARIO"),
	empresaDiretoria("empresa.DIRETORIA"),
	empresaDisciplina("empresa.DISCIPLINA"),
	empresaDtc("empresa.DTC"),
	empresaEmissor("empresa.EMISSOR"),
	empresaEmitente1("empresa.EMITENTE"),
	empresaEquipamento("empresa.EQUIPAMENTO"),
	empresaEquipamentos("empresa.EQUIPAMENTOS"),
	empresaFase("empresa.FASE"),
	empresaFornecedor("empresa.FORNECEDOR"),
	empresaGerencia("empresa.GERENCIA"),
	empresaGuiaRecebimento("empresa.GUIA_RECEBIMENTO"),
	empresaIdioma("empresa.IDIOMA"),
	empresaImpacto01("empresa.IMPACTO_01"),
	empresaImpacto02("empresa.IMPACTO_02"),
	empresaImpacto03("empresa.IMPACTO_03"),
	empresaImpacto04("empresa.IMPACTO_04"),
	empresaLit("empresa.LIT"),
	empresaLocal("empresa.LOCAL"),
	empresaMaterial("empresa.MATERIAL"),
	empresaNatureza("empresa.NATUREZA"),
	empresaNcr("empresa.NCR"),
	empresaNcrro("empresa.NCRRO"),
	empresaNeeddate("empresa.NEEDDATE"),
	empresaNumero("empresa.NUMERO"),
	empresaObs("empresa.OBS"),
	empresaObservacao("empresa.OBSERVACAO"),
	empresaOrdemCompra("empresa.ORDEM_COMPRA"),
	empresaOrigem("empresa.ORIGEM"),
	empresaOther("empresa.OTHER"),
	empresaPo("empresa.PO"),
	empresaPraddendum("empresa.PRADDENDUM"),
	empresaPrazo("empresa.PRAZO"),
	empresaPriority("empresa.PRIORITY"),
	empresaProcesso("empresa.PROCESSO"),
	empresaProduto("empresa.PRODUTO"),
	empresaProjeto("empresa.PROJETO"),
	empresaProposito("empresa.PROPOSITO"),
	empresaReclamacao("empresa.RECLAMACAO"),
	empresaReference("empresa.REFERENCE"),
	empresaReferencia("empresa.REFERENCIA"),
	empresaResp("empresa.RESP"),
	empresaRespondida("empresa.RESPONDIDA"),
	empresaResponsavel("empresa.RESPONSAVEL"),
	empresaResponsible("empresa.RESPONSIBLE"),
	empresaSecao("empresa.SECAO"),
	empresaSeton("empresa.SETON"),
	empresaSetor("empresa.SETOR"),
	empresaStatustdp("empresa.STATUSTDP"),
	empresaSubmarino("empresa.SUBMARINO"),
	empresaSumario("empresa.SUMARIO"),
	empresaTce("empresa.TCE"),
	empresaTipo("empresa.TIPO"),
	empresaTopic0("empresa.TOPIC0"),
	idContrato("empresa.ID_CONTRATO"),
	idDcns("empresa.ID_DCNS"),
	impactoCrono("empresa.IMPACTO_CRONO"),
	impactoHh("empresa.IMPACTO_Hh"),
	impactoMonetario("empresa.IMPACTO_MONETARIO"),
	incResp("empresa.DT_INC_RESP"),
	incTdpis("empresa.DT_INC_TDPIS"),
	itemAcao("empresa.NUMERO_ITEM_ACAO"),
	itemNorma("empresa.ITEM_NORMA"),
	levelDec1("empresa.LEVEL_DEC1"),
	levelDec2("empresa.LEVEL_DEC2"),
	levelDec3("empresa.LEVEL_DEC3"),
	necessidadeAdf("necessidade_adf"),
	necessitaRad("empresa.NECESSITA_RAD"),
	necessitaResp("empresa.NECESSITA_RESP"),
	novoDoc("empresa.NOVO_DOC"),
	numberRef("empresa.NUMBER_REF"),
	numeroTa("empresa.NUMERO_TA"),
	numFornecedor("empresa.NUM_FORNECEDOR"),
	numGrd("empresa.NUM_GRD"),
	objType("empresa.OBJ_TYPE"),
	option("option"),
	ordemCompra("ordem_compra"),
	orgEmissor("empresa.ORG_EMISSOR"),
	orgParticipante("empresa.ORG_PARTICIPANTE"),
	orgResponsavel("empresa.ORG_RESPONSAVEL"),
	outrosParticipantes("empresa.OUTROS_PARTICIPANTES"),
	parecerGerencia("empresa.PARECER_GERENCIA"),
	pedidoCliente("empresa.PEDIDO_CLIENTE"),
	prNumber("empresa.PR_NUMBER"),
	proposito("proposito"),
	questionDate("empresa.QUESTION_DATE"),
	questionEntity("empresa.QUESTION_ENTITY"),
	questionSubject("empresa.QUESTION_SUBJECT"),
	questionWriter("empresa.QUESTION_WRITER"),
	refResp("empresa.DOC_REF_RESP"),
	relActivity("empresa.REL_ACTIVITY"),
	relCos("empresa.REL_COS"),
	rirRelacionada("empresa.RIR_RELACIONADA"),
	role("role"),
	sitFuncional("empresa.SIT_FUNCIONAL"),
	sitGeografica("empresa.SIT_GEOGRAFICA"),
	sitObra("empresa.SIT_OBRA"),
	status("status"),
	statusLibracao("empresa.STATUS_LIBRACAO"),
	statusRir("empresa.STATUS_RIR"),
	taCorretion("empresa.TA_CORRETION"),
	tafCategoria("empresa.TAF_CATEGORIA"),
	tafSubmarino("empresa.TAF_SUBMARINO"),
	tipoDoc("empresa.TIPO_DOC"),
	tipoOutros("empresa.TIPO_OUTROS"),
	treinamentoFim("empresa.DT_TREINAMENTO_FIM"),
	treinamentoIni("empresa.DT_TREINAMENTO_INI"),
	undProd("empresa.UND_PROD"),
	usefulReference("empresa.USEFUL_REFERENCE"),
	valorAgregado("empresa.VALOR_AGREGADO"),
	writerempresa("empresa.WRITER_empresa");	

	private String name;

	private AttributesOthers(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}
	
	public static String attributes() {

		AttributesOthers[] values = AttributesOthers.values();
		StringBuilder valuesString = new StringBuilder();

		for (int i = 0; i < values.length; i++) {
			valuesString.append(values[i] + " ");
		}

		return valuesString.toString();
	}

}
